export interface CountryDialCode {
  country: string;
  code: string;
  flag: string;
  dialCode: string;
  maxLength: number;
}

export const COUNTRY_DIAL_CODES: CountryDialCode[] = [
  { country: "United States", code: "US", flag: "🇺🇸", dialCode: "+1", maxLength: 10 },
  { country: "Canada", code: "CA", flag: "🇨🇦", dialCode: "+1", maxLength: 10 },
  { country: "United Kingdom", code: "GB", flag: "🇬🇧", dialCode: "+44", maxLength: 11 },
  { country: "Australia", code: "AU", flag: "🇦🇺", dialCode: "+61", maxLength: 9 },
  { country: "India", code: "IN", flag: "🇮🇳", dialCode: "+91", maxLength: 10 },
  { country: "United Arab Emirates", code: "AE", flag: "🇦🇪", dialCode: "+971", maxLength: 9 },
  { country: "Saudi Arabia", code: "SA", flag: "🇸🇦", dialCode: "+966", maxLength: 9 },
  { country: "Qatar", code: "QA", flag: "🇶🇦", dialCode: "+974", maxLength: 8 },
  { country: "Kuwait", code: "KW", flag: "🇰🇼", dialCode: "+965", maxLength: 8 },
  { country: "Bahrain", code: "BH", flag: "🇧🇭", dialCode: "+973", maxLength: 8 },
  { country: "Oman", code: "OM", flag: "🇴🇲", dialCode: "+968", maxLength: 8 },
  { country: "Singapore", code: "SG", flag: "🇸🇬", dialCode: "+65", maxLength: 8 },
  { country: "Malaysia", code: "MY", flag: "🇲🇾", dialCode: "+60", maxLength: 10 },
  { country: "New Zealand", code: "NZ", flag: "🇳🇿", dialCode: "+64", maxLength: 10 },
  { country: "Germany", code: "DE", flag: "🇩🇪", dialCode: "+49", maxLength: 11 },
  { country: "France", code: "FR", flag: "🇫🇷", dialCode: "+33", maxLength: 9 },
  { country: "Italy", code: "IT", flag: "🇮🇹", dialCode: "+39", maxLength: 10 },
  { country: "Spain", code: "ES", flag: "🇪🇸", dialCode: "+34", maxLength: 9 },
  { country: "Netherlands", code: "NL", flag: "🇳🇱", dialCode: "+31", maxLength: 9 },
  { country: "Belgium", code: "BE", flag: "🇧🇪", dialCode: "+32", maxLength: 9 },
  { country: "Switzerland", code: "CH", flag: "🇨🇭", dialCode: "+41", maxLength: 9 },
  { country: "Austria", code: "AT", flag: "🇦🇹", dialCode: "+43", maxLength: 10 },
  { country: "Sweden", code: "SE", flag: "🇸🇪", dialCode: "+46", maxLength: 9 },
  { country: "Norway", code: "NO", flag: "🇳🇴", dialCode: "+47", maxLength: 8 },
  { country: "Denmark", code: "DK", flag: "🇩🇰", dialCode: "+45", maxLength: 8 },
  { country: "Finland", code: "FI", flag: "🇫🇮", dialCode: "+358", maxLength: 10 },
  { country: "Ireland", code: "IE", flag: "🇮🇪", dialCode: "+353", maxLength: 9 },
  { country: "Portugal", code: "PT", flag: "🇵🇹", dialCode: "+351", maxLength: 9 },
  { country: "Greece", code: "GR", flag: "🇬🇷", dialCode: "+30", maxLength: 10 },
  { country: "Poland", code: "PL", flag: "🇵🇱", dialCode: "+48", maxLength: 9 },
  { country: "Czech Republic", code: "CZ", flag: "🇨🇿", dialCode: "+420", maxLength: 9 },
  { country: "Romania", code: "RO", flag: "🇷🇴", dialCode: "+40", maxLength: 10 },
  { country: "Hungary", code: "HU", flag: "🇭🇺", dialCode: "+36", maxLength: 9 },
  { country: "Russia", code: "RU", flag: "🇷🇺", dialCode: "+7", maxLength: 10 },
  { country: "Ukraine", code: "UA", flag: "🇺🇦", dialCode: "+380", maxLength: 9 },
  { country: "Turkey", code: "TR", flag: "🇹🇷", dialCode: "+90", maxLength: 10 },
  { country: "Israel", code: "IL", flag: "🇮🇱", dialCode: "+972", maxLength: 9 },
  { country: "South Africa", code: "ZA", flag: "🇿🇦", dialCode: "+27", maxLength: 9 },
  { country: "Nigeria", code: "NG", flag: "🇳🇬", dialCode: "+234", maxLength: 10 },
  { country: "Kenya", code: "KE", flag: "🇰🇪", dialCode: "+254", maxLength: 9 },
  { country: "Egypt", code: "EG", flag: "🇪🇬", dialCode: "+20", maxLength: 10 },
  { country: "Morocco", code: "MA", flag: "🇲🇦", dialCode: "+212", maxLength: 9 },
  { country: "Brazil", code: "BR", flag: "🇧🇷", dialCode: "+55", maxLength: 11 },
  { country: "Mexico", code: "MX", flag: "🇲🇽", dialCode: "+52", maxLength: 10 },
  { country: "Argentina", code: "AR", flag: "🇦🇷", dialCode: "+54", maxLength: 10 },
  { country: "Colombia", code: "CO", flag: "🇨🇴", dialCode: "+57", maxLength: 10 },
  { country: "Chile", code: "CL", flag: "🇨🇱", dialCode: "+56", maxLength: 9 },
  { country: "Peru", code: "PE", flag: "🇵🇪", dialCode: "+51", maxLength: 9 },
  { country: "China", code: "CN", flag: "🇨🇳", dialCode: "+86", maxLength: 11 },
  { country: "Japan", code: "JP", flag: "🇯🇵", dialCode: "+81", maxLength: 10 },
  { country: "South Korea", code: "KR", flag: "🇰🇷", dialCode: "+82", maxLength: 10 },
  { country: "Indonesia", code: "ID", flag: "🇮🇩", dialCode: "+62", maxLength: 12 },
  { country: "Thailand", code: "TH", flag: "🇹🇭", dialCode: "+66", maxLength: 9 },
  { country: "Vietnam", code: "VN", flag: "🇻🇳", dialCode: "+84", maxLength: 9 },
  { country: "Philippines", code: "PH", flag: "🇵🇭", dialCode: "+63", maxLength: 10 },
  { country: "Pakistan", code: "PK", flag: "🇵🇰", dialCode: "+92", maxLength: 10 },
  { country: "Bangladesh", code: "BD", flag: "🇧🇩", dialCode: "+880", maxLength: 10 },
  { country: "Sri Lanka", code: "LK", flag: "🇱🇰", dialCode: "+94", maxLength: 9 },
  { country: "Nepal", code: "NP", flag: "🇳🇵", dialCode: "+977", maxLength: 10 },
];
