import { toast } from 'sonner';
import React, { useState } from 'react'
import { Card, CardContent, CardHeader, CardTitle, CardDescription } from '@/components/ui/card'
import { Button } from '@/components/ui/button'
import { Input } from '@/components/ui/input'
import { Badge } from '@/components/ui/badge'
import { motion } from 'framer-motion'
import { useToast } from '@/components/ui/use-toast'
import { SearchIcon, DownloadIcon, PrinterIcon, Trash2Icon, EyeIcon, FileTextIcon, FileSpreadsheetIcon } from 'lucide-react'
import { exportToExcel, exportToPdf, printPage } from '@/lib/export-utils'


const typeIcon: Record<string, React.ReactNode> = {
  VAT_RETURN: <FileTextIcon className="size-5 text-indigo-500" />,
  VAT_SUMMARY: <FileTextIcon className="size-5 text-amber-500" />,
  SALES_REGISTER: <FileSpreadsheetIcon className="size-5 text-blue-500" />,
  PURCHASE_REGISTER: <FileSpreadsheetIcon className="size-5 text-emerald-500" />,
}

const typeLabels: Record<string, string> = {
  VAT_RETURN: 'VAT Return',
  VAT_SUMMARY: 'VAT Summary',
  SALES_REGISTER: 'Sales Register',
  PURCHASE_REGISTER: 'Purchase Register',
}

export default function StatutoryGeneratedClient() {
  const { toast } = useToast()
  const [search, setSearch] = useState('')
  const [reports, setReports] = useState<any[]>([])
  const [page, setPage] = useState(1)
  const PER_PAGE = 6

  const filtered = reports.filter(r =>
    r.name.toLowerCase().includes(search.toLowerCase()) ||
    r.type.toLowerCase().includes(search.toLowerCase()) ||
    r.period.toLowerCase().includes(search.toLowerCase())
  )

  const totalPages = Math.ceil(filtered.length / PER_PAGE)
  const rows = filtered.slice((page - 1) * PER_PAGE, page * PER_PAGE)

  const handleDelete = (id: string) => {
    setReports(prev => prev.filter(r => r.id !== id))
    toast({ title: 'Report deleted', description: 'The generated report has been removed.' })
  }

  return (
    <div className="p-4 sm:p-8 max-w-7xl mx-auto space-y-8 bg-muted/50 dark:bg-slate-900/50 min-h-screen">
      {/* Header */}
      <div className="flex flex-col md:flex-row justify-between items-start md:items-center gap-4">
        <div>
          <h1 className="text-3xl font-bold tracking-tight bg-gradient-to-r from-blue-600 to-indigo-600 bg-clip-text text-transparent">Generated Reports</h1>
          <p className="text-muted-foreground mt-1">{reports.length} reports available — UAE Tax Engine</p>
        </div>
      </div>

      {/* Summary */}
      <div className="grid grid-cols-2 sm:grid-cols-4 gap-4">
        {[
          { label: 'Total Reports', value: reports.length, color: 'text-foreground dark:text-slate-100' },
          { label: 'VAT Returns', value: reports.filter(r => r.type === 'VAT_RETURN').length, color: 'text-indigo-600' },
          { label: 'Registers', value: reports.filter(r => r.type.includes('REGISTER')).length, color: 'text-blue-600' },
          { label: 'Summaries', value: reports.filter(r => r.type === 'VAT_SUMMARY').length, color: 'text-amber-600' },
        ].map((s, i) => (
          <Card key={i} className="border-none shadow-sm bg-card dark:bg-slate-900">
            <CardContent className="p-5">
              <p className="text-sm text-muted-foreground">{s.label}</p>
              <p className={`text-3xl font-bold mt-1 ${s.color}`}>{s.value}</p>
            </CardContent>
          </Card>
        ))}
      </div>

      {/* Table */}
      <motion.div initial={{ opacity: 0, y: 16 }} animate={{ opacity: 1, y: 0 }} transition={{ duration: 0.4 }}>
        <Card className="border-none shadow-sm bg-card dark:bg-slate-900">
          <CardHeader className="flex flex-col sm:flex-row items-start sm:items-center justify-between gap-3">
            <div>
              <CardTitle>Report History</CardTitle>
              <CardDescription>All previously generated statutory reports</CardDescription>
            </div>
            <div className="relative w-full sm:w-72">
              <SearchIcon className="absolute left-3 top-1/2 -translate-y-1/2 size-4 text-muted-foreground" />
              <Input placeholder="Search reports..." className="pl-9 text-sm" value={search} onChange={e => { setSearch(e.target.value); setPage(1) }} />
            </div>
          </CardHeader>
          <CardContent>
            <div className="overflow-x-auto">
              <table className="w-full text-sm">
                <thead>
                  <tr className="border-b border-border dark:border-slate-800">
                    {['Report Name','Country','Period','Generated By','Generated At','Status','Actions'].map(h => (
                      <th key={h} className="text-left py-3 px-3 text-muted-foreground font-medium whitespace-nowrap">{h}</th>
                    ))}
                  </tr>
                </thead>
                <tbody>
                  {rows.length === 0 && (
                    <tr>
                      <td colSpan={7} className="py-12 text-center text-muted-foreground">
                        <FileTextIcon className="size-8 mx-auto mb-3 text-slate-300 dark:text-foreground" />
                        <p>No generated reports found.</p>
                      </td>
                    </tr>
                  )}
                  {rows.map((r: any) => (
                    <tr key={r.id} className="border-b border-slate-50 dark:border-slate-800/50 hover:bg-muted dark:hover:bg-slate-800/30 transition-colors">
                      <td className="py-3 px-3">
                        <div className="flex items-center gap-2">
                          {typeIcon[r.type]}
                          <div>
                            <p className="font-medium">{r.name}</p>
                            <p className="text-xs text-muted-foreground">{typeLabels[r.type]}</p>
                          </div>
                        </div>
                      </td>
                      <td className="py-3 px-3"><Badge variant="outline">{r.country}</Badge></td>
                      <td className="py-3 px-3 text-muted-foreground whitespace-nowrap">{r.period}</td>
                      <td className="py-3 px-3 font-medium">{r.generatedBy}</td>
                      <td className="py-3 px-3 text-muted-foreground whitespace-nowrap">{r.generatedAt}</td>
                      <td className="py-3 px-3">
                        <Badge className="bg-emerald-100 text-emerald-700 dark:bg-emerald-900/30 dark:text-emerald-400 border-0">{r.status}</Badge>
                      </td>
                      <td className="py-3 px-3">
                        <div className="flex gap-1">
                          <div className="relative group/tip">
                            <Button variant="ghost" size="sm" className="h-7 px-2" onClick={() => toast({ title: 'Viewing report...' })}><EyeIcon className="size-3.5" /></Button>
                            <span className="pointer-events-none absolute -top-8 left-1/2 -translate-x-1/2 whitespace-nowrap rounded bg-slate-800 px-2 py-1 text-xs text-white opacity-0 group-hover/tip:opacity-100 transition-opacity duration-150 z-50">View</span>
                          </div>
                          <div className="relative group/tip">
                            <Button variant="ghost" size="sm" className="h-7 px-2 hover:bg-rose-50 hover:text-rose-600" onClick={() => {
                              const cols = ['Report Name','Country','Period','Generated By','Generated At','Status']
                              const data = [[r.name, r.country, r.period, r.generatedBy, r.generatedAt, r.status]]
                              exportToPdf(r.name, cols, data, r.name.replace(/ /g, '_'))
                            }}><FileTextIcon className="size-3.5 text-rose-500" /></Button>
                            <span className="pointer-events-none absolute -top-8 left-1/2 -translate-x-1/2 whitespace-nowrap rounded bg-rose-700 px-2 py-1 text-xs text-white opacity-0 group-hover/tip:opacity-100 transition-opacity duration-150 z-50">PDF</span>
                          </div>
                          <div className="relative group/tip">
                            <Button variant="ghost" size="sm" className="h-7 px-2 hover:bg-emerald-50 hover:text-emerald-600" onClick={() => {
                              exportToExcel([r], r.name.replace(/ /g, '_'))
                            }}><FileSpreadsheetIcon className="size-3.5 text-emerald-500" /></Button>
                            <span className="pointer-events-none absolute -top-8 left-1/2 -translate-x-1/2 whitespace-nowrap rounded bg-emerald-700 px-2 py-1 text-xs text-white opacity-0 group-hover/tip:opacity-100 transition-opacity duration-150 z-50">Excel</span>
                          </div>
                          <div className="relative group/tip">
                            <Button variant="ghost" size="sm" className="h-7 px-2 text-rose-500 hover:text-rose-600 hover:bg-rose-50 dark:hover:bg-rose-900/20" onClick={() => handleDelete(r.id)}><Trash2Icon className="size-3.5" /></Button>
                            <span className="pointer-events-none absolute -top-8 left-1/2 -translate-x-1/2 whitespace-nowrap rounded bg-slate-800 px-2 py-1 text-xs text-white opacity-0 group-hover/tip:opacity-100 transition-opacity duration-150 z-50">Delete</span>
                          </div>
                        </div>
                      </td>
                    </tr>
                  ))}
                </tbody>
              </table>
            </div>
            <div className="flex items-center justify-between mt-4 pt-4 border-t border-border dark:border-slate-800">
              <p className="text-sm text-muted-foreground">Page {page} of {totalPages || 1}</p>
              <div className="flex gap-2">
                <Button variant="outline" size="sm" disabled={page === 1} onClick={() => setPage(p => p - 1)}>Previous</Button>
                <Button variant="outline" size="sm" disabled={page >= totalPages} onClick={() => setPage(p => p + 1)}>Next</Button>
              </div>
            </div>
          </CardContent>
        </Card>
      </motion.div>
    </div>
  )
}
